version: '3'

services:
  weather-app:
    build:
      context: weather-app
    container_name: weather-app
    entrypoint: npm start
    volumes:
      - ./weather-app:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks: 
      - node-network
    tty: true
    ports:
      - 4000:4000

  # webpage:
  #   build:
  #     context: node
  #   container_name: webpage
  #   entrypoint: npm start
  #   networks: 
  #     - node-network
  #   tty: true
  #   ports:
  #     - 8080:8080
  
  nginx:
    build:
      context: port-website
    container_name: nginx
    restart: always
    volumes:
      - ./port-website:/var/www/html
    networks: 
      - node-network
    tty: true
    ports:
      - 80:80

networks: 
  node-network:
    driver: bridge