version: '3'

services:
  weather-app:
    build:
      context: weather-app
      dockerfile: .docker/Dockerfile
    container_name: weather-app
    entrypoint: npm start
    volumes:
      - ./weather-app:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks: 
      - node-network
    tty: true
    ports:
      - 4000:4000

  boss-machine:
    build:
      context: port-website/expressjs-boss-machine
    container_name: boss-machine
    entrypoint: npm start
    volumes:
      - ./port-website/expressjs-boss-machine:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks: 
      - node-network
    tty: true
    ports:
      - 4001:4001

  
  nginx:
    build:
      context: port-website
      dockerfile: .docker/Dockerfile
    container_name: nginx
    restart: always
    volumes:
      - ./port-website:/var/www/html
    networks: 
      - node-network
    tty: true
    ports:
      - 80:80

networks: 
  node-network:
    driver: bridge