version: '3'

services:
  weather-app:
    build:
      context: weather-app
      dockerfile: .docker/Dockerfile
    container_name: weather-app
    entrypoint: npm start
    volumes:
      - ./weather-app:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    tty: true
    ports:
      - 4000:4000

  boss-machine:
    build:
      context: port-website/boss-machine
    container_name: boss-machine
    entrypoint: npm start
    volumes:
      - ./port-website/boss-machine:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

    tty: true
    ports:
      - 4001:4001

  
  # nginx:
  #   build:
  #     context: port-website
  #     dockerfile: .docker/Dockerfile
  #   container_name: nginx
  #   restart: always
  #   volumes:
  #     - ./port-website:/var/www/html
  #     - ./port-website/nginx:/etc/nginx/conf.d

  #   tty: true
  #   ports:
  #     - 80:80


  app:
    build: nestjs-api
    entrypoint: dockerize -wait tcp://db:5432 -timeout 40s ./.docker/entrypoint.sh
    container_name: app
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    build: nestjs-api/.docker/postgres
    container_name: db
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=blockhub
    volumes:
      - /nest-api/.docker/dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

